name: ci 
on: workflow_dispatch
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip \
dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc \
qemu-utils kpartx gpg pigz
      - run: ./build-docker.sh
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: RPI-ESE-${{ steps.date.outputs.date }}
          path: deploy/*.zip
