name: ci 
on: 
  workflow_dispatch
  schedule:
    - cron: '0 0 10 * *'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install docker.io
      - run: sudo ./build-docker.sh
      - uses: actions/upload-artifact@v3
  	with:
    	name: RPI-ESE-${{ steps.date.outputs.date }}
    	path: deploy/*.zip
